language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - COV=3.7.1
  - COV=4.0
  - COV=4.4
matrix:
  exclude:
    - python: "3.6"
      env: COV=3.7.1
    - python: "3.6"
      env: COV=4.0

# command to install dependencies
install: pip install coverage==$COV

# command to run tests
script:
    - python setup.py install
    - sh scripts/update_assets.sh
    - python -m unittest tests
